version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: testkeycloakpassword
      POSTGRES_USER: testkeycloakuser
      POSTGRES_DB: testkeycloakdb
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: keycloakuser
      KEYCLOAK_ADMIN_PASSWORD: keycloakpassword
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/testkeycloakdb
      KC_DB_USERNAME: testkeycloakuser
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: testkeycloakpassword
      KC_LOG_LEVEL: debug
    ports:
      - 8085:8080
    command:
      - start-dev